name: Master
on:
  push:
    branches:
      - master
jobs:
  dialyzer:
    name: Cache PLT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 23.2
          elixir-version: 1.11
      - name: Get dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Retrieve PLT
        uses: actions/cache@v2
        with:
          path: .dialyzer
          key: plt-master
      - name: Run dialyzer
        run: |
          mix dialyzer
